<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\DB;
use Tests\TestCase;

/**
 * Safety interlock.
 *
 * The suite cannot use RefreshDatabase (about 15 tables were generated by the CMS
 * and have no migration), so it runs against a real MySQL database built from
 * database/dumps/schema.sql. Some tests — the schema-guard ones especially — issue
 * ALTER TABLE, and DDL is not transactional, so DatabaseTransactions cannot roll it
 * back.
 *
 * If phpunit.xml's DB_DATABASE were ever dropped or overridden, those tests would
 * quietly start rewriting the working database instead. This test fails loudly
 * first.
 */
class TestDatabaseIsolationTest extends TestCase
{
    public function test_suite_is_not_pointed_at_the_working_database(): void
    {
        $connected = DB::selectOne('SELECT DATABASE() AS d')->d;

        $this->assertNotSame(
            'bconnect',
            $connected,
            'The test suite is connected to the working database. Check DB_DATABASE in phpunit.xml.'
        );

        $this->assertStringContainsString(
            'testing',
            $connected,
            "Expected a database whose name marks it as disposable; got `{$connected}`."
        );
    }
}
