<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * One recorded intent to buy from Bycel, and the report row eventually claimed for
 * it. See the create_bycel_purchases migration for why this exists.
 *
 * Hand-written and NOT CMS-managed (no cms_pages row), so unlike the App\* models
 * generated by the CMS this file is never regenerated — no
 * /* Start custom functions *\/ markers are needed and nothing here is at risk of
 * being erased by a CMS page save.
 */
class BycelPurchase extends Model
{
    /** Recorded before the POST; outcome not yet known. */
    public const STATE_SENT = 'sent';
    /** A last_pin_report row was matched and claimed for this intent. */
    public const STATE_CLAIMED = 'claimed';
    /** Bycel definitively rejected it, or it was provably never purchased. */
    public const STATE_FAILED = 'failed';
    /** More than one candidate row matched — a human must decide. */
    public const STATE_AMBIGUOUS = 'ambiguous';
    /** An admin declared this intent dead (no purchase happened). */
    public const STATE_ABANDONED = 'abandoned';

    protected $table = 'bycel_purchases';

    protected $guarded = ['id'];

    protected $casts = [
        'watermark_id' => 'integer',
        'merchant_purchase_id' => 'integer',
        'snapshot' => 'array',
        'report_row' => 'array',
        'cost_lbp' => 'decimal:4',
        'discount_percentage' => 'decimal:4',
        'request_at' => 'datetime',
        'response_at' => 'datetime',
        'claimed_at' => 'datetime',
    ];

    public function order()
    {
        return $this->belongsTo(Order::class, 'order_id');
    }

    /** Still awaiting an outcome — what the reconciler sweeps. */
    public function isOpen(): bool
    {
        return $this->state === self::STATE_SENT;
    }

    public function isResolved(): bool
    {
        return in_array($this->state, [self::STATE_CLAIMED, self::STATE_FAILED, self::STATE_ABANDONED], true);
    }
}
