<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One immutable line in the credit audit trail.
 *
 * Plain App\ model, NOT generated by the CMS and with no cms_pages row — so it has
 * no cms_draft_flag global scope and the CMS schema editor cannot touch it.
 *
 * Entries are append-only. A mistake is corrected by writing a compensating
 * `correction` entry, never by editing or deleting an existing row: the whole point
 * is that the history cannot be quietly rewritten.
 */
class CreditLedgerEntry extends Model
{
    // Debits (negative amount)
    public const REASON_ORDER_PLACED = 'order_placed';
    public const REASON_ORDER_REDEBIT = 'order_redebit';
    public const REASON_TOPUP_REVERTED = 'topup_reverted';

    // Credits (positive amount)
    public const REASON_ORDER_REFUND = 'order_refund';
    public const REASON_TOPUP_APPROVED = 'topup_approved';
    public const REASON_SUPPLIER_REFUND = 'supplier_refund';
    public const REASON_OPENING_BALANCE = 'opening_balance';

    // Either direction
    public const REASON_ADMIN_ADJUSTMENT = 'admin_adjustment';
    public const REASON_CORRECTION = 'correction';

    public const ACTOR_USER = 'user';
    public const ACTOR_ADMIN = 'admin';
    public const ACTOR_SYSTEM = 'system';

    protected $table = 'credit_ledger_entries';

    protected $guarded = ['id'];

    protected $casts = [
        'amount' => 'decimal:4',
        'balance_after' => 'decimal:4',
        'meta' => 'array',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'user_id');
    }

    /** The order or credits-transfer this entry was caused by, when there is one. */
    public function source()
    {
        return $this->morphTo(__FUNCTION__, 'source_type', 'source_id');
    }

    /** Human-readable label for the CMS/admin views. */
    public function getReasonLabelAttribute(): string
    {
        return ucfirst(str_replace('_', ' ', $this->reason));
    }
}
